### ISSUE TITLE
Reached milestone 0.11, next stop 1.0

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#113]
[Changelog 0.11 in the wiki](https://github.com/webpack/docs/wiki/changelog#011)
- All important features are done
- Plugin system is so rich, that most features can be implemented as plugins
- Performance is good
- devtools are good

From 0.11 to 1.0
- [x] Bug fixes
- [x] small additional options for existing features
- [x] Documentation, presentation, more examples (help needed)
- [x] Pimp README
- [x] update [analyse tool](http://webpack.github.io/analyse)
- [x] keep up to date with dependencies
- [x] Feedback about readiness for 1.0 (help needed)
- [x] move some options into plugins
- [x] more tests

After 1.0
- Even better documentation (help needed)
- Marketing :smile: (help needed)
- Adding source map support to loaders and the root library (jade, less, css)
