### ISSUE TITLE
RFC: Webpack Diagnostics Meta Data

### ISSUE THREAD

**Issue by quanru** [webpack/webpack#17067]
Feature request
What is the expected behavior?
Hope that webpack can provide a built-in data structure for analysis and diagnosis.

What is motivation or use case for adding/changing the behavior?
The existing stats data is not conducive to building analysis and diagnosis. In order to deeply analyze the entire webpack building process, developers often need to do some extra work to reassemble a data structure, such as
- Data Collection
  - Intercept loader to collect the loader data, for querying the loader that the file has passed through, as well as the time and intermediate products of each loader.
  - Intercept compiler/compilation hooks to collect the plugin data,  for recording the running order and running time of external plugins in hooks
  - Reassembling resolver data, for tracking the process status of compiling all paths within the project, aiming to help users identify how the erroneous path is generated.
  - Stringify the final effective webpack configuration
- Data Processing
  - Generate chunk graph
  - Generate module graph
  - Generate package graph
- Data Display
  - Write front-end pages to display processed data in a user-friendly interface and assist users in troubleshooting problems through visual aids.
- Data Diagnosis
  - Writing rules to take processed data as input and output diagnostic results, such as
    - Duplicate Packages
    - Default Import Check
    - Loader Performance Optimization

How should this be implemented in your opinion?
1. Design a standardized diagnostic data structure and rule mechanism that allows developers to investigate the building process and develop rules around this data structure. Use a configuration switch to enable the generation of this data structure.
2. Develop a webpack plugin that reads this data through a diagnostic service and provides users with front-end page troubleshooting and diagnosis:
  1. Compile Analysis
    1. Webpack Loaders: Investigate and analyze Webpack Loaders-related call data and time-consuming information
    2. Webpack Plugins: Query the number of calls and time of Webpack Compiler / Compilation Hooks
    3. Module Resolve: Help you quickly query the final path after the module path of an import/require in a file is parsed
  2. Bundle Analysis
    1. Bundle Size: The volume data, first screen resource size, duplicate package, module reference relationship and other information of the current compiled product
    2. Tree Shaking: Help you further analyze and investigate the tree shaking bailout reason of a file in the project
- Prototype Page
  - Overall: In addition to giving an overall overview, we will also provide a Bundle Alerts module to scan for problems to be fixed through rules, such as duplicate package detection. It supports the tracing of each duplicate package introduction chain.
![image](https://user-images.githubusercontent.com/11739753/234492082-c1acb696-20f7-4cbe-8bed-eabdd13deca5.png)
  - Loader: Show the loader timing diagram, as well as the loader time consumption and changes before and after the loader of each module.It not only supports viewing the Loaders details of a single file, but also supports viewing the Loaders data of the file directory.
![image](https://user-images.githubusercontent.com/11739753/234492105-b5dddf54-e5c7-4fba-acea-77433884282f.png)
![image](https://user-images.githubusercontent.com/11739753/234492131-da767e02-5b25-4801-9655-dd05fad82985.png)

  - Plugin: Support to view the call data information of all plug-in-in-used Compiler Hooks and Compilation Hooks in the current Webpack project
![image](https://user-images.githubusercontent.com/11739753/234492160-ae0799d0-d0a3-463b-b41b-ac57bd024c56.png)

  - Bundle: Show the parsed size of each module, that is, the volume actually packaged into the bundle product.
![image](https://user-images.githubusercontent.com/11739753/234492186-4ff4f9b0-79ba-4081-8927-3b2ad84aee89.png)
![image](https://user-images.githubusercontent.com/11739753/234492200-0baccd6d-25e8-40f9-8805-3cd465d1d518.png)

  - Tree shaking: You can know the reason why the code is not shaken for reasons such as "where variables are used" through it.
![image](https://user-images.githubusercontent.com/11739753/234492236-55365271-338d-4080-9fc0-ccd727aebaed.png)

Are you willing to work on this yourself?
yes

**Comment by TheLarkInn** [comment]
Currently we don't have structured data to report on hinting. See (https://github.com/webpack/webpack/issues/17122). I'm 100% on board with this. I think we need to break.

**Comment by easy1090** [comment]
已收到，谢谢~~

**Comment by TheLarkInn** [comment]
This proposal can allow us to create a structural format for Optimization Bailouts instead of strings.

**Comment by TheLarkInn** [comment]
This RFC Work should be broken down into (at least) two pieces: 
- [ ] Restructure Data Format to accomplish 
  - [ ] Add additional data structures in Stats
  - [ ] Additional Profiling API's can be stored in https://github.com/webpack/webpack/blob/main/lib/ModuleProfile.js
- [ ] Creation of the UI/Reporting (Plugin)

Should we have a format for Vite/Parcel/webpack/rspack/esbuild/etc/Prior Work
- https://bundle-buddy.com
- https://github.com/relative-ci/bundle-stats
- https://github.com/statoscope/statoscope

**Comment by quanru** [comment]
Hi~ @TheLarkInn @alexander-akait !

We are trying to count the time spent by each Loader. Since the Loader does not expose the Hook, we need to consult the Core Team about the implementation method. Currently, we have three candidate solutions:
- Solution 1: Write a official built-in webpack plugin, which traverses all module.rules and inserts our proxy-loader, sample code:

``` ts
// Plugin
export class InternalLoaderPlugin {
  public readonly name = 'loader';

  public apply(compiler: Compiler) {
    compiler.hooks.afterPlugins.tap(this.tapPostOptions, this.afterPlugins);
  }

  public afterPlugins = (compiler: Compiler) => {
    if (compiler.isChild()) return;
    // intercept loader to collect the costs of loaders
    compiler.options.module.rules = interceptLoader(
      compiler.options.module.rules as RuleSetRule[],
      require.resolve('../loader-proxy')
    );
  };
}

// loader-proxy
const loaderModule: LoaderDefinition<ProxyLoaderOptions> = function (...args) {
  if (shouldSkipLoader(this)) {
    this.callback(null, ...args);
    return;
  }

  this.cacheable(false);

  const mod = getOriginLoaderModule(this);

  if (mod.default) {
    // https://webpack.js.org/api/loaders/#raw-loader
    if (mod.raw === false && Buffer.isBuffer(args[0])) {
      args[0] = args[0].toString();
    }

    let start: number;
    let startHRTime: [number, number];

    const trap = BuildUtils.createLoaderContextTrap.call(this, (err, res, sourceMap) => {
      reportLoader(this, start, startHRTime, false, false, args[0].toString(), err, res, sourceMap);
    });

    start = Date.now();
    startHRTime = process.hrtime();

    try {
      const result = mod.default.apply(trap, args);

      // sync function
      if (result) {
        if (!(result instanceof Promise)) {
          reportLoader(this, start, startHRTime, false, true, args[0].toString(), null, result);
        }
      }

      return result;
    } catch (error) {
      reportLoader(this, start, startHRTime, false, true, args[0].toString(), error as Error, null);
      throw error;
    }
  }
  this.callback(null, ...args);
};

loaderModule.pitch = function () {
  if (shouldSkipLoader(this)) {
    return;
  }

  this.cacheable(false);

  const mod = getOriginLoaderModule(this);

  if (mod.pitch && typeof mod.pitch === 'function') {
    let start: number;
    let startHRTime: [number, number];

    const trap = BuildUtils.createLoaderContextTrap.call(this, (err, res) => {
      reportLoader(this, start, startHRTime, true, false, err ? 'Loader Pitch Async Error' : '', err, res);
    });

    start = Date.now();
    startHRTime = process.hrtime();

    try {
      // @ts-ignore
      const res = mod.pitch.apply(trap, arguments);

      // with pitch result
      if (res) {
        if (!(res instanceof Promise)) {
          reportLoader(this, start, startHRTime, true, true, '', null, res);
        }
      }

      return res;
    } catch (error) {
      reportLoader(this, start, startHRTime, true, true, 'Loader Pitch Sync Error', error as Error, null);
      throw error;
    }
  }
};

// set `raw: true` for every resources, so that can control the result for the correct loader.
// @ts-ignore
loaderModule.raw = true;

// @ts-ignore
export = loaderModule;

```

- Solution 2: Directly insert the logic of solution 1 before and after the actual loader in the place where webpack processing configs, such as https://github.com/webpack/webpack/blob/main/lib/config/normalization.js#L242 
- Solution 3: Modify the https://github.com/webpack/loader-runner to expose the hook of a single loader

Do you have any suggestions? Is there a more suitable implementation method? I need your guidance~

**Comment by hardfist** [comment]
@alexander-akait friendly ping, any suggestions for us?
