### ISSUE TITLE
Webpack Hints 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#17122]
- [x] #11695 
- [x] Notify (warn) user to use `optimization.runtimeChunk: true` when runtime is in a large chunk ( Example: #12145 ) 
- [x] Notify (warn) user to that a _added rule_ RuleSet/Loader is unused
- [x] Optimization Bailouts (Generalized). "Weird optimization bailouts" (@sokra?)
- [ ] Default configuration (@sokra?)
- [x] `[not cacheable]` Where and why the hell does this show up? Report on it? Stats Printer? (Example: #748)
- [x] Warn when multiple versions of library appear in one build (Example: #385) 
- [x] [NEED TO CONFIRM] - Notify (?) when user _dosn't_ use OS neutral RegExp (Example: #2553)
- [x] `Did you mean ...` error when a module isn't found (Low priority - Help Wanted) (Example: #5543)
- [x] Force users to provide name for cache when in MultiCompiler mode (#15460), Potentially Rework Approach
- [x] "Hints are disabled in green" (@sokra ?)
- [ ] Keep a hash of hints as random seed to select the hint + make more deterministic 
- [x] `stats.hints: number | false | true`

**Comment by TheLarkInn** [comment]
Let's reorder this by priority once @sokra responds to some of the ? issue items.

**Comment by webvs2** [comment]
I'll see if I can help with the problem

**Comment by payal723** [comment]
Hello! I'm a new contributor and would like to work on this issue. 

I want to start by adding the warning for missing leading dots in `resolve.extensions`.

Could you please guide me on where to begin? Thank you!

**Comment by alexander-akait** [comment]
Most of them closed, I still work on more hints, but I think we can close it, resolved here all what is possible
