### ISSUE TITLE
Update Loader README's for each loader for v2. Update Loader/Plugin Maintainer Guideline

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3195]
- Update any loaders in org. to have code examples using `rules` instead of `loaders` in config examples. 
- Update loaders to use es6 `export default` export instead of `module.exports`
  - Requires major release for each loader.
- Update/Create Loader/Plugin Maintainer Guide (create separate issue)
- Fix license to match with the one in webpack/webpack (it changed since with moved to JS Foundation).

**To-do list (added by @spacek33z):**

Prepare PR's for README's for the most common repo's:

- [x] [webpack](https://github.com/webpack/webpack)
- [x] [css-loader](https://github.com/webpack/css-loader)
- [x] [json-loader](https://github.com/webpack/json-loader)
- [x] [less-loader](https://github.com/webpack/less-loader)
- [x] [raw-loader](https://github.com/webpack/raw-loader)
- [x] [node-loader](https://github.com/webpack/node-loader)
- [x] [style-loader](https://github.com/webpack/style-loader)
- [x] [file-loader](https://github.com/webpack/file-loader)
- [x] [url-loader](https://github.com/webpack/url-loader)
- [x] [source-map-loader](https://github.com/webpack/source-map-loader)
- [x] [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware)
- [x] [webpack-dev-server](https://github.com/webpack/webpack-dev-server)

**Comment by michael-ciniawsky** [comment]
@TheLarkInn 👍 I can take/work on this one

[Core README Draft](https://github.com/michael-ciniawsky/webpack/tree/readme)
[Loader/Plugin README Boilerplate](https://github.com/michael-ciniawsky/README)

- Could you please host the new logo (e.g gh-pages in webpack/media) so I can update it?
- What LICENSE if missing in some loader repos is the correct one from now on (foundation requirement etc.) ?
- There was some nebulous CLA signment rumor, if needed where/how do I need to do that?

I would make one loader && plugin README update, come back here, if approved that way, then do it for the rest 😛  👍 ?

**Comment by SpaceK33z** [comment]
@michael-ciniawsky, nice work on the loader readme. Some feedback:

- I'd remove the license text in the readme, it's already present as a file. Or maybe reference to that file at least. That way we're sure both are the exact same version.
- Maybe some standardised format to show the available options?
- A specific example in webpack.config.js would be nice, so not all loaders use a completely different one. Something like this maybe:

```js
module: {
    rules: [
        {
            test: /\.json$/,
            loader: 'json-loader',
            options: {
                foo: 'bar'
            }
        }
}
```

About the CLA signment thingy, there is a bot that will automatically ask you for this when you do a PR.

**Comment by michael-ciniawsky** [comment]
@SpaceK33z  yep the README boilerplate is  currently  'outdated'

#### webpack-loaders

> I'd remove the license text in the readme, it's already present as a file. Or maybe reference to that file at least. That way we're sure both are the exact same version.

Like you said LICENSE appendix -> Github UI 

> Maybe some standardised format to show the available options?

Definitely, this is WIP when I start updating, bc I need to check all the options of the various loaders first and find a readable format/pattern for that :)

> A specific example in webpack.config.js would be nice, so not all loaders use a completely different one. Something like this maybe:

:+1 Should the {String} based e.g `require(some-loader?option=value!./file.ext)` options vanish completely or leave a short example mentioning that it's possible, but use `webpack.config.js`  is recommended and 'best practice' ?

Can you or someone of the core team please host the new logo in webpack/media, so I can use it in README and Loader README ? Or in any prefered wayform your side, as long as I have access to it somehow 😛 


#### webpack-plugins

Is it possible/planned/intended in the future to extract the Core Plugins from webpack/webpack and give them there own repos (e.g like extract-text-plugin, compression-plugin)? Since I update the README's anyways, let's do that in one blow then... :)

#### webpack 

Do you mind take a look at the webpack README posted above aswell? e.g

- You are missing as core member atm (will be fixed asap :)) 
- Add CONTRIBUTORS Section like MAINTAINERS under the MAINTAINERS section, but with sponsors && backers && maintainers && contributors it gets also bloated, so not sure about that 
- The example section needs an update aswell imo, but not sure how at best
- What you have in mind 😛 
- Maybe even remove all the loader tables and try to match the structure of the new docs better somehow (Still thinking about the how)

#### webpack-dev-server/webpack-dev-middleware 

- Find a logo for them, do you have something in mind? Currently I would go with standard server icon + webpack-logo for dev-server and expressjs logo + webpack-logo for dev-middleware?
- Can you provide me an overview of all options for both of them, especially `webpack-dev-server`

### loader-utils/loader-runner/tapable/memory-fs/enhance-resolve

What is the way forward there, will the structure stay like that in the near future ? Especially loader-utils is important for docs update.

What is your general opinion on making a loader-, plugin-boilerplate ? The README Boilerplate should not stay on a random joe's (me) profile and only a README repo at webpack org is not recommended/useful either.

**Comment by SpaceK33z** [comment]
> Definitely, this is WIP when I start updating, bc I need to check all the options of the various loaders first and find a readable format/pattern for that :)

Cool. If you want any help updating some loaders, let me know. Note that some loaders have specific maintainers, so it would maybe be nice to communicate with them beforehand about this.

> :+1 Should the {String} based e.g require(some-loader?option=value!./file.ext) options vanish completely or leave a short example mentioning that it's possible, but use webpack.config.js is recommended and 'best practice' ?

I don't know if we should vanish string based require's completely, but via `webpack.config.js` is definitely recommended.

> Can you or someone of the core team please host the new logo in webpack/media, so I can use it in README and Loader README ? Or in any prefered wayform your side, as long as I have access to it somehow 😛

I made an issue for it: webpack/webpack.js.org/issues/297, since it should be hosted on webpack.js.org.

> Is it possible/planned/intended in the future to extract the Core Plugins from webpack/webpack and give them there own repos (e.g like extract-text-plugin, compression-plugin)? Since I update the README's anyways, let's do that in one blow then... :)

As far as I know, there are no plans to do this short-term, at least not in v2. So this wouldn't be necessary.

> webpack-dev-server/webpack-dev-middleware
> Find a logo for them, do you have something in mind? Currently I would go with standard server icon + webpack-logo for dev-server and expressjs logo + webpack-logo for dev-middleware?

Note that I'm the maintainer of those two packages. I would like to do the README's for those two packages myself; although if you really want to it's fine of course.

WDM will gain support for other servers then Express.js soon, so that logo would be misplaced. I can't currently think of another icon type though :(.

> Can you provide me an overview of all options for both of them, especially webpack-dev-server

All options for WDM and WDS are documented on [the new webpack docs](https://webpack.js.org/configuration/dev-server/), so I think we should just link to there. This is a "special" case however.

> loader-utils/loader-runner/tapable/memory-fs/enhance-resolve
> What is the way forward there, will the structure stay like that in the near future ? Especially loader-utils is important for docs update.

I think of those packages, only loader-utils is important for now because it's used by many loader authors. The rest we can do later. We can change the structure of the README to be more like the loader boilerplate.

> What is your general opinion on making a loader-, plugin-boilerplate ?

Hmm, I think a separate repo might seem like a good idea at first, but that it will be forgotten. I'd say that the readme's can be copied from a random other loader, since all of them will follow the same readme boilerplate. That's just my opinion though ;).

Awesome to see that you're taking this seriously 💯. The whole webpack community will be thankful. In many of the loader repo's there are open issues asking what the loader does exactly.

**Comment by michael-ciniawsky** [comment]
> Cool. If you want any help updating some loaders, let me know. Note that some loaders have specific maintainers, so it would maybe be nice to communicate with them beforehand about this.

Yep, of course all respective maintainers need to approve and maybe rework/refine content for the respective loader then, but first of all a general structure/style/start must be established, that's were I come into play :). Content changes and refinements is up to mantainers anyways, I will try to update content where mostly missing atm aswell, but possible that for some loaders their maintainers need to provide the actual content 😛 .I ask for/discuss that in the PR's later with them :).

> I made an issue for it: webpack/webpack.js.org#297, since it should be hosted on webpack.js.org.

👍 thx I will keep track of that issue, hopefully soon, so I can start 🚀 

> I don't know if we should vanish string based require's completely, but via webpack.config.js is definitely recommended and we should be clear that this is the way to go in most cases.

ok I will provide a absolute basic example of a `require(loader!./file.ext)` in terms of 'inline' usage, but if folks start to complain about it, can be removed by the maintainers anytime afterwards. Main is `webpack.config.js` webpack v2 style

> All options for WDM and WDS are documented on the new webpack docs, so I think we should just link to there. This is a "special" case however.

Yep, you got me here, I just looked at the README's and recapped want I now from my daily usage, will take info/content from there: 👍 

> Note that I'm the maintainer of those two packages. I would like to do the README's for those two packages myself; although if you really want to it's fine of course.

I know 😛 , awesome job there so far 💯 👍 . Well in the end it's your decision , there is enough to do, like stated above, have it consisted is the/my/our main goal, I can send it so you don't have to do all the chore, just go over the content then and refine where inappropriated. Or pick (the soon to be updated) README Boilerplate and do as you please :).  

> WDM will gain support for other servers then Express.js soon, so that logo would be misplaced. I can't currently think of another icon type though :(.

Ok I have absolutely no insight whats being planned there ;). Maybe there is a generic icon/logo like the typical 'standard' server icon, we'll see or just leave it atm.

> I think of those packages, only loader-utils is important for now because it's used by many loader authors. The rest we can do later. We can change the structure of the README to be more like the loader boilerplate.

Yep, agreed loader-utils is the important one, thb I'm also not really capable to write docs about the other ones 👀 . sokra can add JSDoc to them, when he is in the mood 😆 

> As far as I know, there are no plans to do this short-term, at least not in v2. So this wouldn't be necessary.

kk

> Hmm, I think a separate repo might seem like a good idea at first, but that it will be forgotten. I'd say that the readme's can be copied from a random other loader, since all of them will follow the same readme boilerplate. That's just my opinion though ;).

Yeah sadly there is truth to that, for e.g postcss-plugin-boilerplate is avaiable but every new plugin I see never uses it 😢 . But it also doesn't really get promoted, so maybe if the docs for loader/plugin authors would mentioned it, more dev would use/adopt it ¯\_(ツ)_/¯. Still discussable though... also not 'urgent' atm.

The webpack README update currently in progress, whats the opinion/issues/complains there ? 

I will start with style-, css-, file-, url-, raw-loader, but come here again after the first README is finished for discussion and general style approvement from webpack/core-team. ok ?

**Comment by SpaceK33z** [comment]
> The webpack README update currently in progress, whats the opinion/issues/complains there ?

- I think it should be `npm install --save-dev webpack` instead of `npm i -D webpack`. While the latter is shorter, beginners don't always know what `i` or `-D` means. And we don't want to confuse them so early :).
- `Bundles both CommonJS and AMD modules (even combined).` since webpack v2 it also bundles ES Modules. Maybe put that up first, since it's the "new thing".
- The example given is very advanced, and may confuse / scare beginners. Maybe make clear that this is something "advanced"? As you said previously, we could also rework it to be simpler.
- For webpack v2 the links are different (moved to webpack.js.org and have a new structure). We could also fix this later though.
- I'd only refer to the license file in the readme here too.
- The loader tables are fine here for now I think. It shows off how big the webpack ecosystem is and that there is support for everything you can imagine 🌈 .
- As you said, I'd also like to be added in the maintainers table ;).
- Agree with you that adding the contributors section might get too bloated. Perhaps GitHub provides a nice page where all contributors are listed? Then we can link to that.

Over all, nice work on the webpack readme. It's a lot better!

> I will start with style-, css-, file-, url-, raw-loader, but come here again after the first README is finished for discussion and general style approvement from webpack/core-team. ok ?

Sure, I'll give you feedback and will try to get at least one other core member to do it too 😃 .

**Comment by michael-ciniawsky** [comment]
> I think it should be npm install --save-dev webpack instead of npm i -D webpack. While the latter is shorter, beginners don't always know what i or -D means. And we don't want to confuse them so early :).

👍 

> Bundles both CommonJS and AMD modules (even combined). since webpack v2 it also bundles ES Modules. Maybe put that up first, since it's the "new thing".

kk. I will add/extrapolate webpack's native ES6 Modules/System.import support.

> The example given is very advanced, and may confuse / scare beginners. Maybe make clear that this is something "advanced"? As you said previously, we could also rework it to be simpler.

kk, I will try to find another one (example from docs splash page, simple config intro etc.), but substance to discuss later on.

> For webpack v2 the links are different (moved to webpack.js.org and have a new structure). We could also fix this later though.

I will take a look at the new docs and align structure (README chapters) with them, where possible, as I intended with the old docs :). When is depending on how long it will approximately take for v2 to be released, I have it in mind, but true maybe links could be set later.

> I'd only refer to the license file in the readme here too.

Yep same as in README Boilerplate -> outdated, will be removed.

> The loader tables are fine here for now I think. It shows off how big the webpack ecosystem is and that there is support for everything you can imagine 🌈 .

kk I will add at least one table for 'common' plugins under plugins aswell then. Any sugesstions for important/recommended/most used plugins, besides the core, extract-text, compression plugin(s)?

> As you said, I'd also like to be added in the maintainers table ;)

For sure 😛 

> Agree with you that adding the contributors section might get too bloated. Perhaps GitHub provides a nice page where all contributors are listed? Then we can link to that.

kk discarded, backers and sponsors are enough to signal community importance/friendliness/size

Contributors => Github UI :)

> Sure, I'll give you feedback and will try to get at least one other core member to do it too 😃 .

👍 Appreciated

**Comment by michael-ciniawsky** [comment]
ping :)

**Comment by SpaceK33z** [comment]
@michael-ciniawsky done! See https://webpack.js.org/branding/

**Comment by michael-ciniawsky** [comment]
@SpaceK33z thx 👍 on it from now. Finish webpack/webpack, then a smaller one like json-loader for style approvement like discussed, when approved style-, css-, less- , file, url-, raw-loader, + loader-utils next :)

**Comment by TheLarkInn** [comment]
@michael-ciniawsky do you have an update on this. We are interested in having this for v2 release. If you need help we can enlist the @webpack/contributor-team to help with this migration process.

**Comment by michael-ciniawsky** [comment]
@TheLarkInn I'm sry for the delay, but I'm commited to social work from time to time, I'm back home tonight and if you and @webpack/core-team agrees, I will send PR's with at least the structural/style updates + the ones I have basically finished (in terms of content). You can start reviewing them then and if meanwhile someone from @webpack/contributor-team wants to pick an unfinished one, just fine, merge in and he/she can finish/update contents based on that and send PR 👍 . Otherwise PR stays open as WIP for me :).

**Comment by michael-ciniawsky** [comment]
[webpack](https://github.com/michael-ciniawsky/webpack/tree/readme)

- I would like to slightly update the structure to match better with webpack.js.org
- Any missing plugins/loaders in the repective lists (I will check webpack.js.org/[loader || plugins])
- Is the example basically ok ? To complicated for beginners etc..?

**Comment by TheLarkInn** [comment]
No problem!!!!! @SpaceK33z Do you wanna follow up with this.

**Comment by SpaceK33z** [comment]
@michael-ciniawsky, I made a PR to your repo which brings the readme up-to-date with the latest changes and fixes a couple of small issues I had with it. The rest looks very good. I'm not completely sure about the advanced example. We could remove it and just link to the [Get started](https://webpack.js.org/get-started/) page. But let's just leave in for now so we can focus on the loader README's.

**Comment by michael-ciniawsky** [comment]
@SpaceK33z 

>I'm not completely sure about the advanced example

Yep same here, I can add an basic example (getting started) above the advance one, subject to change nevertheless.

>  But let's just leave in for now so we can focus on the loader README's

Currently working on it PR's coming during the day 😛

**Comment by simon04** [comment]
Since webpack 2 is out and all tasks (https://github.com/webpack/webpack/issues/3195#issue-185402561) are done, can this issue be closed?

**Comment by michael-ciniawsky** [comment]
@simon04 I think so, a few loaders @webpack-contrib are missing but I have unfinished work regarding that and push when I have time
