### ISSUE TITLE
Add semver & changelog generation to webpack & plugins

### ISSUE THREAD

**Issue by wardpeet** [webpack/webpack#4104]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Add [semantic-release](https://github.com/semantic-release/semantic-release) and [cz-converntion-changelog](https://github.com/commitizen/cz-conventional-changelog) to help maintainability of webpack repositories.

- [ ] [memory-fs](http://github.com/webpack/memory-fs) - [#36](https://github.com/webpack/memory-fs/pull/36)
- [ ] [enhanced-resolve](http://github.com/webpack/enhanced-resolve) - [#63](https://github.com/webpack/enhanced-resolve/pull/63)
- [ ] [tapable](http://github.com/webpack/tapable) - [#26](https://github.com/webpack/tapable/pull/26)
- [x] [webpack-sources](http://github.com/webpack/webpack-sources) - [#12](https://github.com/webpack/webpack-sources/pull/12)
- [ ] [source-list-map](https://github.com/webpack/source-list-map) - [#9](https://github.com/webpack/source-list-map/pull/9)
- [ ] [watchpack](http://github.com/webpack/watchpack) - [#49](https://github.com/webpack/watchpack/pull/49/files)
- [ ] [loader-runner](http://github.com/webpack/loader-runner) - [#14](https://github.com/webpack/loader-runner/pull/14)
- [x] [loader-utils](https://github.com/webpack/loader-utils) - [#78](https://github.com/webpack/loader-utils/pull/78)
- [ ] [node-libs-browser](http://github.com/webpack/node-libs-browser) - [#54](https://github.com/webpack/node-libs-browser/pull/54)
- [ ] [webpack.js.org](http://github.com/webpack/webpack.js.org) - [#1017](https://github.com/webpack/webpack.js.org/pull/1017)
- [ ] [webpack-cli](http://github.com/webpack/webpack-cli) @webpack/contributor-team should work together on this (maybe issue submitted first)
- [ ] [webpack](http://github.com/webpack/webpack) @webpack/core-team needs to decide first

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Create new release more easy with a good changelog

**If this is a feature request, what is motivation or use case for changing the behavior?**
@TheLarkInn told me about this issue and it would make the life of the maintainers more easy.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
I'm going to remove canary because that's in webpack-contrib

**Comment by wardpeet** [comment]
thanks do you have any preset in mind?
I'll push a version in a few versions with angular preset lots of stuff is being missed because of merge commits

**Comment by TheLarkInn** [comment]
Open to great suggestions, or maybe start with one repo and we can fine tune to apply the rest

**Comment by wardpeet** [comment]
Best to start with one repo in my opinion and migrate the rest afterwards.

I'll play with some changelogs to see what seems best.

**Comment by michael-ciniawsky** [comment]
[standard-version](https://github.com/conventional-changelog/standard-version)  || [standard-changelog](https://github.com/conventional-changelog/standard-changelog) [part of standard-version] instead of cz-conventional-changelog. The fromer is also for releases while the latter is `CHANGELOG.md` only. `standard` => Angular Commit Convention (changelog-angular-preset)

**Comment by TheLarkInn** [comment]
@wardpeet Sorry I forgot to mention lets start with supporting package first, and webpack last. I need to discuss with @webpack/core-team if we want to do auto deploy for webpack core.

**Comment by TheLarkInn** [comment]
@webpack/contributor-team Those who are working on the `webpack-cli` would you work with @wardpeet when it comes time to implement this in webpack-cli? I know you guys have stuff on your plate already so just to sync up with an issue in that repo is a good start first. 

@wardpeet leave `webpack-cli` and `webpack` last to be decided.

**Comment by wardpeet** [comment]
@TheLarkInn starting with tapable :)

**Comment by d3viant0ne** [comment]
@wardpeet - Hang on a minute

**Comment by d3viant0ne** [comment]
There is a group discussing standard tooling already and I have to agree with @michael-ciniawsky here.

Standard version has a smoother release cycle & allows for `alpha || beta || rc tags` which is something Webpack does quite a bit of.

**Comment by TheLarkInn** [comment]
Yeah I think thats a good direction. As long as it still provides the same auto deploy benefits of `semantic-release`, I'm fine with that.

**Comment by wardpeet** [comment]
I was looking into standard-version instead of conventional-changelog :)

**Comment by d3viant0ne** [comment]
Standard version negates the need for semantic-release as well. No fuss, single command `npm run release` and you get the tag, changelog and cookies and milk

**Comment by wardpeet** [comment]
yes but downside I have at the moment that they use (angular format)[https://github.com/conventional-changelog/standard-version#commit-message-convention-at-a-glance] which does not work for these packages.

**Comment by d3viant0ne** [comment]
Why would we not use the angular commit message conventions?

**Comment by wardpeet** [comment]
It won't convert old commit messages ^^.

**Comment by d3viant0ne** [comment]
Nothing a little `git rebase -i` and  some reword can't fix should we choose to.

**Comment by wardpeet** [comment]
great :) didn't know you were going to do that ^^.
I'll cook up a few PRS :)

**Comment by wardpeet** [comment]
first one is created:
https://github.com/webpack/tapable/pull/26

**Comment by d3viant0ne** [comment]
@wardpeet - If you are bored or just want to get those daily contribs up, feel free to apply the same to everything in `webpack-contrib` that doesn't have it.

**Comment by wardpeet** [comment]
yes will create them everywhere :)
have some time today anyway. Feel free to comment or take over

**Comment by wardpeet** [comment]
@d3viant0ne do you want me to do the same like you did for all repo's?

**Comment by d3viant0ne** [comment]
No need for the docs. They are now in https://webpack.js.org/development/release-process/ 

We only need to reference the release docs somewhere

**Comment by sokra** [comment]
Here are my opinions regarding this topics: https://gist.github.com/sokra/bc283d7f931c9f59f33e18dd35c851f4

**Comment by wardpeet** [comment]
great, i'm doing all the changelogs today :)

**Comment by wardpeet** [comment]
@sokra so what's your take on it?

**Comment by wardpeet** [comment]
@sokra so what's your take on it?

**Comment by wardpeet** [comment]
@d3viant0ne @TheLarkInn updated all repo's
